module.exports = (grunt) ->
  grunt.initConfig
      coffee:
        compile:
          files:
            'js/_bookmark_bubble.js': ['coffee/_bookmark_bubble.coffee']
      concat: 
        options:
          banner: "/* this file is generated by concat task of grunt */\n"
        dist:
          src: ['mobile-bookmark-bubble/bookmark_bubble.js', 'js/_bookmark_bubble.js']
          dest: 'js/mobile_bookmark_bubble.js'
          
      uglify:
        minify:
          options:
            mangle: true
            preserveComments: 'all'
          files:
            'js/mobile_bookmark_bubble.min.js': ['mobile-bookmark-bubble/bookmark_bubble.js', 'js/_bookmark_bubble.js']

    grunt.loadNpmTasks 'grunt-contrib-coffee'
    grunt.loadNpmTasks 'grunt-contrib-concat'
    grunt.loadNpmTasks 'grunt-contrib-uglify'
    grunt.registerTask 'default', [
      'coffee',
      'concat',
      'uglify'
    ]
